config/routes.rb
Rails.application.routes.draw do

  get 'faker', to: 'faker#fake', as: 'faker'
  get 'fakeoff', to: 'faker#fakeOff', as: 'fakeoff'

  get 'start_training/:id', to: 'mqtt#start_training', as: 'start_training'
  get 'stop_training/:id', to: 'mqtt#stop_training', as: 'stop_training'

  get 'activities', to: 'activities#index', as: 'activities'
  get 'activities/:id', to: 'activities#show', as: 'activity'

  get 'participants', to: 'participants#index', as: 'participants'
  get 'participants/:id', to: 'participants#show', as: 'participant'

  get 'static/homepage' => 'static#homepage', as: 'homepage'

  get 'user_edit',  to:'users#edit', as: 'user_edit'
  put 'user_update/:id', to:'users#update', as: 'user_update'
  put 'updateAAR/:id', to: 'trainings#updateAAR', as:'updateAAR'



  devise_for :users, controllers: {
       registrations: 'users/registrations'

     }
     devise_scope :user do
       root :to => 'devise/sessions#new'
     end
  resources :users
  resources :trainees
  resources :trainings
  root 'static#homepage'
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :trainee
  belongs_to :training
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController

  def index
    puts "params[:trainingId] is #{params[:trainingId]}"
    #Return only participants who are currently selected
    @participants = Participant.where(:training_id => params[:trainingId])

    respond_to do |format|
      format.json  { render :json => @participants }
    end
  end

  def show
    @participant = Participant.find(params[:id])
    respond_to do |format|
      format.json  { render :json => @participant }
    end
  end

end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= form_for(participant) do |f| %>
  <% if participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% participant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :calories_burnt %>
    <%= f.number_field :calories_burnt %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<h1>Editing Participant</h1>

<%= render 'form', participant: @participant %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Participants</h1>

<table>
  <thead>
    <tr>
      <th>Calories burnt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= participant.calories_burnt %></td>
        <td><%= link_to 'Show', participant %></td>
        <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
        <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/new.html.erb
<h1>New Participant</h1>

<%= render 'form', participant: @participant %>

<%= link_to 'Back', participants_path %>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Calories burnt:</strong>
  <%= @participant.calories_burnt %>
</p>

<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>